server.port=9090
profile.name=Nsikak Bassey Okon
profile.email=nsikakabasiinam7@gmail.com
profile.stack=Java/Spring Boot
cat.fact.url=https://catfact.ninja/fact
spring.jackson.serialization.indent_output=true
